version: '3.1'

services:
  application:
    container_name: simple-application
    build:
      context: .
      dockerfile: docker/application/Dockerfile
    volumes:
      - ./code:/var/www/html
    links:
      - elastic
    depends_on:
      - elastic
    ports:
      - 8888:80
    restart: always
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.1
    container_name: simple-elastic
    environment:
      - cluster.name=docker-cluster
      - node.name=es1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./data/esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', '-u', 'elastic:changeme', 'http://localhost:9200']

